import { createContext, useCallback, useContext, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { meetingApi, recordingApi, transcriptionApi, type AudioDevices, type Meeting, type RecordingStatus, type StartRecordingOptions, type TranscriptSearchResult, type TranscriptSegment, type TranscriptionModelStatus } from "./meetingApi";
import "./App.css";

type View = "home" | "meetings" | "record" | "settings";
type IconName = "home" | "meetings" | "record" | "settings" | "search" | "plus" | "clock" | "sparkles" | "shield" | "headphones" | "chevron";
const paths: Record<IconName, ReactNode> = {
  home: <><path d="m3 11 9-8 9 8" /><path d="M5 10v10h14V10M9 20v-6h6v6" /></>,
  meetings: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M16 3v4M8 3v4M3 10h18" /></>,
  record: <><circle cx="12" cy="12" r="9" /><circle cx="12" cy="12" r="3.5" fill="currentColor" stroke="none" /></>,
  settings: <><circle cx="12" cy="12" r="3" /><path d="M19 15a2 2 0 0 0 .4 2.2l-2.2 2.2A2 2 0 0 0 15 19a2 2 0 0 0-1.2 1.8h-3.2A2 2 0 0 0 9 19a2 2 0 0 0-2.2.4l-2.2-2.2A2 2 0 0 0 5 15a2 2 0 0 0-1.8-1.2v-3.2A2 2 0 0 0 5 9a2 2 0 0 0-.4-2.2l2.2-2.2A2 2 0 0 0 9 5a2 2 0 0 0 1.2-1.8h3.2A2 2 0 0 0 15 5a2 2 0 0 0 2.2-.4l2.2 2.2A2 2 0 0 0 19 9a2 2 0 0 0 1.8 1.2v3.2A2 2 0 0 0 19 15Z" /></>,
  search: <><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></>,
  plus: <path d="M12 5v14M5 12h14" />,
  clock: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></>,
  sparkles: <><path d="m12 3 1.1 3.1L16 7.5l-2.9 1.4L12 12l-1.1-3.1L8 7.5l2.9-1.4L12 3Z" /><path d="m5.5 13 .8 2.2 2.2.8-2.2.8L5.5 19l-.8-2.2-2.2-.8 2.2-.8.8-2.2Z" /></>,
  shield: <><path d="M12 3 5 6v5c0 4.7 2.8 8.2 7 10 4.2-1.8 7-5.3 7-10V6l-7-3Z" /><path d="m9 12 2 2 4-4" /></>,
  headphones: <><path d="M4 14v-2a8 8 0 0 1 16 0v2M6 13H4a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h2v-7ZM18 13h2a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-2v-7Z" /></>,
  chevron: <path d="m9 18 6-6-6-6" />,
};
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
const navItems = [
  { id: "home" as View, label: "Home", icon: "home" as IconName },
  { id: "meetings" as View, label: "Meetings", icon: "meetings" as IconName },
  { id: "record" as View, label: "Record", icon: "record" as IconName },
  { id: "settings" as View, label: "Settings", icon: "settings" as IconName },
];
const TranscriptActions = createContext<{ open: (meeting: Meeting) => void; transcribe: (meeting: Meeting) => void; transcribingId: string | null }>({ open: () => undefined, transcribe: () => undefined, transcribingId: null });
const humanDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const durationLabel = (value: number | null) => value ? `${Math.max(1, Math.round(value / 60_000))} min` : "Not recorded";

function EmptyLibrary({ onRecord }: { onRecord: () => void }) {
  return <div className="empty-state"><div className="empty-visual" aria-hidden="true"><span className="paper back" /><span className="paper front"><i /><i /><i /><b><i /><i /><i /><i /><i /></b></span><span className="empty-spark one">✦</span><span className="empty-spark two">✦</span></div><h3>Your meeting library starts here</h3><p>Prepare a consented recording and it will be stored in your private local library.</p><button className="secondary-button" type="button" onClick={onRecord}><Icon name="record" size={17} /> Record your first meeting</button></div>;
}

function MeetingCard({ meeting, onChanged, onError }: { meeting: Meeting; onChanged: () => Promise<void>; onError: (value: string) => void }) {
  const transcriptActions = useContext(TranscriptActions);
  const run = async (action: () => Promise<unknown>) => { try { await action(); await onChanged(); } catch (error) { onError(String(error)); } };
  const rename = () => { const title = window.prompt("Meeting title", meeting.title); if (title?.trim() && title.trim() !== meeting.title) void run(() => meetingApi.rename(meeting.id, title)); };
  const editTags = () => { const value = window.prompt("Comma-separated tags", meeting.tags.join(", ")); if (value !== null) void run(() => meetingApi.replaceTags(meeting.id, value.split(","))); };
  const remove = () => { if (window.confirm(`Permanently delete “${meeting.title}” and all local data?`)) void run(() => meetingApi.delete(meeting.id)); };
  const play = (track: "mic" | "system") => { void recordingApi.play(meeting.id, track).catch((error) => onError(String(error))); };
  if (meeting.state === "failed" && meeting.recordingPath) {
    return <article className="meeting-card recovery-card"><div className="meeting-card-main"><div className="state-mark archived"><Icon name="record" size={18} /></div><div><div className="meeting-title-line"><h3>{meeting.title}</h3><span className="state-badge archived">recovered</span></div><p>{humanDate(meeting.createdAt)} · Safe audio chunks are available</p></div></div><div className="meeting-actions"><button type="button" onClick={() => play("mic")}>Play mic</button><button type="button" onClick={() => play("system")}>Play system</button><button className="prominent" type="button" disabled={transcriptActions.transcribingId === meeting.id} onClick={() => transcriptActions.transcribe(meeting)}>{transcriptActions.transcribingId === meeting.id ? "Retrying…" : "Retry transcript"}</button><button type="button" onClick={() => void run(() => meetingApi.archive(meeting.id))}>Archive</button></div></article>;
  }
  return <article className="meeting-card"><div className="meeting-card-main"><div className={`state-mark ${meeting.state}`}><Icon name={meeting.state === "ready" ? "sparkles" : "record"} size={18} /></div><div><div className="meeting-title-line"><h3>{meeting.title}</h3><span className={`state-badge ${meeting.state}`}>{meeting.state}</span></div><p>{humanDate(meeting.createdAt)} · {durationLabel(meeting.durationMs)}{meeting.transcriptSegmentCount > 0 ? ` · ${meeting.transcriptSegmentCount} transcript segments` : ""}</p>{meeting.tags.length > 0 && <div className="tag-row">{meeting.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>}</div></div><div className="meeting-actions">{meeting.state === "ready" && meeting.recordingPath && <><button type="button" onClick={() => play("mic")}>Play mic</button><button type="button" onClick={() => play("system")}>Play system</button>{meeting.transcriptSegmentCount > 0 ? <button className="prominent" type="button" onClick={() => transcriptActions.open(meeting)}>Transcript</button> : <button className="prominent" type="button" disabled={transcriptActions.transcribingId === meeting.id} onClick={() => transcriptActions.transcribe(meeting)}>{transcriptActions.transcribingId === meeting.id ? "Transcribing…" : "Transcribe"}</button>}</>}{meeting.state !== "archived" ? <><button type="button" onClick={rename}>Rename</button><button type="button" onClick={editTags}>Tags</button><button type="button" onClick={() => void run(() => meetingApi.archive(meeting.id))}>Archive</button></> : <><button type="button" onClick={() => void run(() => meetingApi.reopen(meeting.id))}>Reopen</button><button className="danger" type="button" onClick={remove}>Delete</button></>}</div></article>;
}

function RecordSetup({ onStart, onError }: { onStart: (title: string, options: StartRecordingOptions) => Promise<void>; onError: (value: string) => void }) {
  const [title, setTitle] = useState(""); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [mode, setMode] = useState<StartRecordingOptions["mode"]>("both"); const [echoCancellation, setEchoCancellation] = useState(true); const [devices, setDevices] = useState<AudioDevices | null>(null); const [micSource, setMicSource] = useState(""); const [systemSource, setSystemSource] = useState("");
  useEffect(() => { if (!recordingApi.available) return; void recordingApi.devices().then((found) => { setDevices(found); setMicSource(found.defaultSource); setSystemSource(found.systemSource ?? ""); }).catch((error) => onError(String(error))); }, [onError]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await onStart(title.trim() || `Meeting ${new Date().toLocaleString()}`, { mode, micSource: micSource || null, systemSource: systemSource || null, echoCancellation: mode === "both" && echoCancellation }); } catch (error) { onError(String(error)); } finally { setBusy(false); } };
  return <section className="page-view record-view"><div className="page-heading"><div><p className="eyebrow">NEW RECORDING</p><h1>Prepare your meeting</h1><p>Choose audio sources and confirm consent before capture begins.</p></div></div><form className="setup-card" onSubmit={(event) => void submit(event)}><label className="field"><span>Meeting title</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Weekly sync" /></label><label className="field"><span>Capture mode</span><select value={mode} onChange={(event) => setMode(event.target.value as StartRecordingOptions["mode"])}><option value="both">Microphone + system audio</option><option value="mic">Microphone only</option><option value="system">System audio only</option></select></label>{devices && mode !== "system" && <label className="field"><span>Microphone</span><select value={micSource} onChange={(event) => setMicSource(event.target.value)}>{devices.sources.filter((source) => !source.monitor).map((source) => <option value={source.name} key={source.name}>{source.name === devices.defaultSource ? `Default · ${source.name}` : source.name}</option>)}</select></label>}{devices && mode !== "mic" && <label className="field"><span>System audio</span><select value={systemSource} onChange={(event) => setSystemSource(event.target.value)}>{devices.sources.filter((source) => source.monitor).map((source) => <option value={source.name} key={source.name}>{source.name === devices.systemSource ? `Default · ${source.name}` : source.name}</option>)}</select></label>}<div className="capture-summary"><Icon name="headphones" size={24} /><div><strong>{mode === "both" ? "Microphone + system audio" : mode === "mic" ? "Microphone only" : "System audio only"}</strong><span>{mode === "both" && echoCancellation ? "WebRTC echo cancellation · headset recommended" : "Original audio is preserved locally"}</span></div></div>{mode === "both" && <label className="inline-check"><input type="checkbox" checked={echoCancellation} onChange={(event) => setEchoCancellation(event.target.checked)} /> Reduce speaker echo (recommended)</label>}<label className="consent-check"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span><strong>I confirm everyone has consented to this recording.</strong><small>You are responsible for following applicable laws and meeting policies.</small></span></label>{!recordingApi.available && <p className="desktop-only-note">Open the Tauri desktop app to capture audio. Browser preview does not access your microphone.</p>}<button className="primary-button record-action" type="submit" disabled={!consent || busy || !recordingApi.available}><Icon name="record" size={18} />{busy ? "Starting…" : "Start recording"}</button></form></section>;
}

const clockLabel = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
function ActiveRecording({ meeting, status, onStop, onTogglePause }: { meeting: Meeting; status: RecordingStatus; onStop: () => Promise<void>; onTogglePause: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  const stop = async () => { setBusy(true); try { await onStop(); } finally { setBusy(false); } };
  const togglePause = async () => { setBusy(true); try { await onTogglePause(); } finally { setBusy(false); } };
  return <section className={`recording-live${status.paused ? " paused" : ""}`} aria-live="polite"><div className="recording-pulse"><span /></div><p className="eyebrow">{status.paused ? "RECORDING PAUSED" : "RECORDING NOW"}</p><h1>{meeting.title}</h1><strong className="recording-clock">{clockLabel(status.elapsedSeconds)}</strong><p>{status.paused ? "Audio capture is paused. Resume when the conversation continues." : "Selected audio sources are being saved in recoverable local chunks."}</p>{status.levels.length > 0 && <div className="level-list" aria-label="Live audio levels">{status.levels.filter((level) => level.name !== "mic_raw").map((level) => <div className="level-row" key={level.name}><span>{level.name === "mic" ? "Microphone" : "System"}</span><i><b style={{ width: `${Math.max(2, Math.round(level.peak * 100))}%` }} /></i></div>)}</div>}{status.storageAvailableBytes !== null && status.storageAvailableBytes < 512 * 1024 * 1024 && <div className="message error">Storage is running low ({Math.round(status.storageAvailableBytes / 1024 / 1024)} MB free). Capture will stop safely at 128 MB.</div>}{!status.processRunning && <div className="message error">An audio device disconnected or the capture process stopped. Stop now to preserve completed chunks.</div>}<div className="recording-controls"><button className="pause-button" type="button" disabled={busy} onClick={() => void togglePause()}>{status.paused ? "Resume" : "Pause"}</button><button className="stop-button" type="button" disabled={busy} onClick={() => void stop()}>{busy ? "Working safely…" : "Stop recording"}</button></div><small>Stopping may take a few seconds while WAV headers and the session manifest are finalized.</small></section>;
}

const timestampLabel = (milliseconds: number) => `${String(Math.floor(milliseconds / 60_000)).padStart(2, "0")}:${String(Math.floor(milliseconds / 1000) % 60).padStart(2, "0")}`;
function TranscriptDialog({ meeting, segments, onClose }: { meeting: Meeting; segments: TranscriptSegment[]; onClose: () => void }) {
  const [exported, setExported] = useState("");
  const [current, setCurrent] = useState(segments);
  const [editing, setEditing] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const exportTranscript = async (format: "markdown" | "text") => setExported(await transcriptionApi.export(meeting.id, format));
  const beginEdit = (segment: TranscriptSegment) => { setEditing(segment.id); setDraft(segment.displayText); };
  const saveEdit = async (segment: TranscriptSegment) => { const corrected = await transcriptionApi.correct(segment.id, draft); setCurrent((items) => items.map((item) => item.id === segment.id ? { ...item, displayText: corrected.displayText, activeCorrectionId: corrected.activeCorrectionId } : item)); setEditing(null); };
  return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="transcript-dialog" role="dialog" aria-modal="true" aria-labelledby="transcript-title" onMouseDown={(event) => event.stopPropagation()}><div className="transcript-header"><div><p className="eyebrow">REVIEW TRANSCRIPT</p><h2 id="transcript-title">{meeting.title}</h2><p>{current.length} timestamped segments · generated locally</p></div><div className="transcript-header-actions"><button type="button" onClick={() => void exportTranscript("markdown")}>Export .md</button><button type="button" onClick={() => void exportTranscript("text")}>Export .txt</button><button type="button" onClick={onClose}>Close</button></div></div>{exported && <p className="export-path">Saved to {exported}</p>}<div className="transcript-body">{current.length === 0 ? <p>No speech was detected in this recording.</p> : current.map((segment) => <article key={segment.id}><button type="button" title="Play matching audio" onClick={() => void recordingApi.play(meeting.id, "mic", segment.startMs)}>{timestampLabel(segment.startMs)}</button><div><div className="segment-heading"><strong>{segment.speakerLabel ?? "Speaker"}</strong>{editing !== segment.id && <button type="button" onClick={() => beginEdit(segment)}>Edit</button>}</div>{editing === segment.id ? <div className="segment-editor"><textarea aria-label="Corrected transcript text" value={draft} onChange={(event) => setDraft(event.target.value)} /><div><button type="button" onClick={() => setEditing(null)}>Cancel</button><button type="button" disabled={!draft.trim()} onClick={() => void saveEdit(segment)}>Save correction</button></div></div> : <><p>{segment.displayText}</p>{segment.activeCorrectionId && <details><summary>Show preserved original</summary><p>{segment.sourceText}</p></details>}</>}</div></article>)}</div><p className="evidence-note"><Icon name="shield" size={15} /> Corrections create a new revision; original transcription evidence is never overwritten.</p></section></div>;
}

function SettingsView({ onSaved }: { onSaved: () => void }) {
  const [reminder, setReminder] = useState(() => localStorage.getItem("transcrip-it.headset-reminder") !== "false");
  const [retention, setRetention] = useState(() => localStorage.getItem("transcrip-it.retention") ?? "forever");
  const [model, setModel] = useState<TranscriptionModelStatus | null>(null);
  const [installing, setInstalling] = useState(false);
  useEffect(() => { void transcriptionApi.modelStatus().then(setModel); }, []);
  const installModel = async () => { setInstalling(true); try { setModel(await transcriptionApi.installModel()); onSaved(); } finally { setInstalling(false); } };
  const save = (event: FormEvent) => { event.preventDefault(); localStorage.setItem("transcrip-it.headset-reminder", String(reminder)); localStorage.setItem("transcrip-it.retention", retention); onSaved(); };
  return <section className="page-view"><div className="page-heading"><div><p className="eyebrow">LOCAL PREFERENCES</p><h1>Settings</h1><p>Control recording guidance, local models, and retention.</p></div></div><form className="settings-card" onSubmit={save}><div className="setting-row"><div><strong>Headset reminder</strong><span>Show the audio-quality reminder before recording.</span></div><input aria-label="Headset reminder" type="checkbox" checked={reminder} onChange={(event) => setReminder(event.target.checked)} /></div><div className="setting-row"><div><strong>{model?.pack ?? "Balanced English"} model</strong><span>{model?.installed ? `${Math.round((model.modelBytes ?? 0) / 1024 / 1024)} MB · ${model.engineVersion}` : "Not installed · approximately 142 MB"}</span></div>{model?.installed ? <span className="model-status installed">Installed</span> : <button className="secondary-button" type="button" disabled={installing || !transcriptionApi.available} onClick={() => void installModel()}>{installing ? "Installing…" : "Install model"}</button>}</div><label className="setting-row"><div><strong>Keep meeting data</strong><span>Automatic retention will never remove data before this period.</span></div><select value={retention} onChange={(event) => setRetention(event.target.value)}><option value="forever">Until I delete it</option><option value="365">One year</option><option value="90">90 days</option><option value="30">30 days</option></select></label><div className="privacy-setting"><Icon name="shield" /><div><strong>Local processing is on</strong><span>Meeting content is not sent to a cloud service.</span></div></div><button className="primary-button" type="submit">Save settings</button></form></section>;
}

function App() {
  const [activeView, setActiveView] = useState<View>("home"); const [meetings, setMeetings] = useState<Meeting[]>([]); const [includeArchived, setIncludeArchived] = useState(false); const [search, setSearch] = useState(""); const [transcriptMatches, setTranscriptMatches] = useState<TranscriptSearchResult[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [recordingMeeting, setRecordingMeeting] = useState<Meeting | null>(null); const [recordingStatus, setRecordingStatus] = useState<RecordingStatus | null>(null); const [transcribingId, setTranscribingId] = useState<string | null>(null); const [openTranscript, setOpenTranscript] = useState<{ meeting: Meeting; segments: TranscriptSegment[] } | null>(null);
  const loadMeetings = useCallback(async () => { setLoading(true); try { setMeetings(await meetingApi.list(includeArchived)); setError(""); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } }, [includeArchived]);
  useEffect(() => { void loadMeetings(); }, [loadMeetings]);
  useEffect(() => { if (!recordingApi.available) return; void recordingApi.status().then(async (status) => { if (status.active && status.meetingId) { const found = (await meetingApi.list(true)).find((meeting) => meeting.id === status.meetingId); if (found) { setRecordingMeeting(found); setRecordingStatus(status); setActiveView("record"); } } }).catch((reason) => setError(String(reason))); }, []);
  useEffect(() => { if (!recordingMeeting) return; const timer = window.setInterval(() => { void recordingApi.status().then(setRecordingStatus).catch((reason) => setError(String(reason))); }, 1000); return () => window.clearInterval(timer); }, [recordingMeeting]);
  useEffect(() => { const timer = window.setTimeout(() => { void transcriptionApi.search(search).then(setTranscriptMatches).catch((reason) => setError(String(reason))); }, 180); return () => window.clearTimeout(timer); }, [search]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return query ? meetings.filter((meeting) => `${meeting.title} ${meeting.tags.join(" ")}`.toLowerCase().includes(query)) : meetings; }, [meetings, search]);
  const goToRecord = () => setActiveView("record");
  const startRecording = async (title: string, options: StartRecordingOptions) => { const id = crypto.randomUUID(); const meeting = await meetingApi.create({ id, idempotencyKey: `create-${id}`, title }); try { const status = await recordingApi.start(id, true, options); setRecordingMeeting({ ...meeting, state: "recording" }); setRecordingStatus(status); await loadMeetings(); } catch (reason) { await loadMeetings(); throw reason; } };
  const stopRecording = async () => { if (!recordingMeeting) return; const completed = await recordingApi.stop(recordingMeeting.id); setRecordingMeeting(null); setRecordingStatus(null); await loadMeetings(); setNotice(`Recording saved locally (${durationLabel(completed.durationMs)}).`); setActiveView("meetings"); };
  const togglePause = async () => { if (!recordingMeeting || !recordingStatus) return; const status = recordingStatus.paused ? await recordingApi.resume(recordingMeeting.id) : await recordingApi.pause(recordingMeeting.id); setRecordingStatus(status); };
  const viewTranscript = async (meeting: Meeting) => { try { setOpenTranscript({ meeting, segments: await transcriptionApi.list(meeting.id) }); } catch (reason) { setError(String(reason)); } };
  const transcribe = async (meeting: Meeting) => { setTranscribingId(meeting.id); setNotice("Transcribing locally. Audio and text stay on this device."); try { const segments = await transcriptionApi.transcribe(meeting.id); await loadMeetings(); setOpenTranscript({ meeting: { ...meeting, transcriptSegmentCount: segments.length }, segments }); setNotice("Local transcription complete."); } catch (reason) { setError(String(reason)); await loadMeetings(); } finally { setTranscribingId(null); } };
  const openSearchResult = (result: TranscriptSearchResult) => { const meeting = meetings.find((candidate) => candidate.id === result.meetingId); if (meeting) void viewTranscript(meeting); };
  const recordedMinutes = Math.round(meetings.reduce((sum, meeting) => sum + (meeting.durationMs ?? 0), 0) / 60_000);
  return <TranscriptActions.Provider value={{ open: (meeting) => void viewTranscript(meeting), transcribe: (meeting) => void transcribe(meeting), transcribingId }}><div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark" aria-hidden="true"><span /><span /><span /><span /><span /></div><span>Transcrip<span className="brand-accent">·it</span></span></div><nav className="primary-nav" aria-label="Primary navigation">{navItems.map((item) => <button className={activeView === item.id ? "nav-item active" : "nav-item"} key={item.id} onClick={() => setActiveView(item.id)} type="button"><Icon name={item.icon} /><span>{item.label}</span></button>)}</nav><div className="sidebar-footer"><div className="local-status"><span className="status-dot" /><div><strong>Local workspace</strong><span>Your data stays on this device</span></div></div><div className="storage-row"><span>Meetings</span><span>{meetings.length} local</span></div><div className="storage-track"><span /></div></div></aside>
    <main className="main-panel"><header className="topbar"><div className="mobile-brand">Transcrip<span>·it</span></div><label className="search-box"><Icon name="search" size={18} /><span className="sr-only">Search meetings</span><input type="search" placeholder="Search meetings…" value={search} onChange={(event) => setSearch(event.target.value)} onFocus={() => setActiveView("meetings")} /><kbd>⌘ K</kbd></label><div className="privacy-pill"><Icon name="shield" size={16} /> Private by default</div><button className="avatar" type="button" aria-label="Local profile">JA</button></header>
      <div className="content">{error && <div className="message error" role="alert">{error}<button type="button" onClick={() => setError("")}>Dismiss</button></div>}{notice && <div className="message success" role="status">{notice}<button type="button" onClick={() => setNotice("")}>Dismiss</button></div>}
        {activeView === "home" && <><section className="hero-row"><div><p className="eyebrow">YOUR MEETING WORKSPACE</p><h1>Good morning</h1><p className="hero-copy">Capture the conversation. Keep the important parts.</p></div><button className="primary-button" type="button" onClick={goToRecord}><Icon name="plus" size={18} /> New recording</button></section><section className="metric-grid" aria-label="Workspace summary"><article className="metric-card"><div className="metric-icon violet"><Icon name="clock" /></div><div><span>MEETINGS</span><strong>{meetings.filter((meeting) => meeting.state !== "archived").length}</strong><small>Local</small></div></article><article className="metric-card"><div className="metric-icon blue"><Icon name="record" /></div><div><span>RECORDED</span><strong>{recordedMinutes}m</strong><small>All time</small></div></article><article className="metric-card"><div className="metric-icon amber"><Icon name="sparkles" /></div><div><span>READY</span><strong>{meetings.filter((meeting) => meeting.state === "ready").length}</strong><small>Meetings</small></div></article></section><section className="headset-card"><div className="headset-art"><Icon name="headphones" size={29} /></div><div className="headset-copy"><span className="recommended-badge">RECOMMENDED</span><h2>Use a headset for the clearest transcript</h2><p>A headset helps separate your voice from meeting audio and improves speaker accuracy.</p></div><button className="text-button" type="button" onClick={() => setActiveView("settings")}>Audio settings <Icon name="chevron" size={16} /></button></section><section className="section-block"><div className="section-heading"><div><h2>Recent meetings</h2><p>Your latest local meetings.</p></div><button className="text-button" type="button" onClick={() => setActiveView("meetings")}>View all <Icon name="chevron" size={16} /></button></div>{loading ? <p className="loading-copy">Loading your library…</p> : meetings.length === 0 ? <EmptyLibrary onRecord={goToRecord} /> : <div className="meeting-list">{meetings.slice(0, 3).map((meeting) => <MeetingCard key={meeting.id} meeting={meeting} onChanged={loadMeetings} onError={setError} />)}</div>}</section></>}
        {activeView === "meetings" && <section className="page-view"><div className="page-heading"><div><p className="eyebrow">LOCAL LIBRARY</p><h1>Meetings</h1><p>Organize, archive, and permanently remove recordings stored on this device.</p></div><button className="primary-button" type="button" onClick={goToRecord}><Icon name="plus" size={18} /> New recording</button></div><label className="archive-toggle"><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.target.checked)} /> Show archived meetings</label>{loading ? <p className="loading-copy">Loading your library…</p> : filtered.length === 0 ? <EmptyLibrary onRecord={goToRecord} /> : <div className="meeting-list">{filtered.map((meeting) => <MeetingCard key={meeting.id} meeting={meeting} onChanged={loadMeetings} onError={setError} />)}</div>}</section>}
        {activeView === "record" && (recordingMeeting && recordingStatus ? <ActiveRecording meeting={recordingMeeting} status={recordingStatus} onStop={stopRecording} onTogglePause={togglePause} /> : <RecordSetup onStart={startRecording} onError={setError} />)}{activeView === "settings" && <SettingsView onSaved={() => setNotice("Settings saved on this device.")} />}
        {activeView === "meetings" && search.trim().length >= 2 && transcriptMatches.length > 0 && <section className="search-results"><h2>Transcript matches</h2>{transcriptMatches.map((result) => <button type="button" key={result.segmentId} onClick={() => openSearchResult(result)}><span><strong>{result.meetingTitle}</strong><small>{timestampLabel(result.startMs)}</small></span><p>{result.snippet.replaceAll("<mark>", "").replaceAll("</mark>", "")}</p></button>)}</section>}
      </div></main>
    <nav className="mobile-nav" aria-label="Mobile navigation">{navItems.map((item) => <button className={activeView === item.id ? "active" : ""} key={item.id} onClick={() => setActiveView(item.id)} type="button"><Icon name={item.icon} size={19} /><span>{item.label}</span></button>)}</nav>
    {openTranscript && <TranscriptDialog meeting={openTranscript.meeting} segments={openTranscript.segments} onClose={() => setOpenTranscript(null)} />}
  </div></TranscriptActions.Provider>;
}

export default App;
